name: release

on:
  workflow_dispatch:

jobs:
  image:
    name: release image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: setup go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.21"

      - name: get repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
        id: repo

      - name: docker login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ steps.repo.outputs.REPO }}:${{ github.sha }}"
